<a href="https://colab.research.google.com/github/cjimenez275/Simulacion_Fisica/blob/main/4_matematica_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 4
* Vectores
* Matrices
* Ecuaciones diferenciales

In [ ]:

from matplotlib import pyplot as plt
import numpy as np


## Vectores

In [ ]:
v1 = np.array([1, 3])
v2 = np.array([5, -4])
v3 = np.array([-7, 1])
print(v1)
print(v2)
print(v3)

[1 3]
[ 5 -4]
[-7  1]


In [ ]:
print(v1 + v2)
print(np.dot(v1,v3))

[ 6 -1]
-4


## Matrices

In [ ]:
#Multiplicacion y suma
z = np.array([[1, 3], [-1, 10]])
w = np.array([[2, 4], [1, -3]])

print("La matriz z es: ")
print(z)
print("La matriz w es: ")
print(w)

suma = w + z
print("La matriz w + z es: ")
print(suma)

result = np.dot(z,w)
print("La matriz z por w es: ")
print(result)



La matriz z es: 
[[ 1  3]
 [-1 10]]
La matriz w es: 
[[ 2  4]
 [ 1 -3]]
La matriz w + z es: 
[[3 7]
 [0 7]]
La matriz z por w es: 
[[  5  -5]
 [  8 -34]]


In [ ]:
m1 = np.array([[1, 3],[4, -2]])
m2 = np.array([[-1, 0],[5, 3]])


#Transpuesta
t = m1.transpose()
print("La matriz es: ")
print(m1)
print("Y su transpuesta es: ")
print(t)

La matriz es: 
[[ 1  3]
 [ 4 -2]]
Y su transpuesta es: 
[[ 1  4]
 [ 3 -2]]


In [ ]:
# Autovectores y autovalores
from numpy import linalg as LA
print("La matriz es: ")
print(m1)
eigenval, eigenvec = LA.eig(m1)
print("Sus autovalores son: ")
print(eigenval)
print("Sus autovectores son: ")
print(eigenvec)

La matriz es: 
[[ 1  3]
 [ 4 -2]]
Sus autovalores son: 
[ 3.27491722 -4.27491722]
Sus autovectores son: 
[[ 0.79681209 -0.49436913]
 [ 0.60422718  0.86925207]]


In [ ]:

#Construccion y modificación de matrices

z = np.zeros((3,4))
print(z)
for i in range(3):
    for j in range(4):
        z[i][j] = i**2-j

print("z modificado es: ")
print(z)
print("El elemento z[1,3] es: ", z[1,3])
print(z[1][3])


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
z modificado es: 
[[ 0. -1. -2. -3.]
 [ 1.  0. -1. -2.]
 [ 4.  3.  2.  1.]]
El elemento z[1,3] es:  -2.0
-2.0


In [ ]:

# Tensores

w = np.ones((3,4,2))
print("El tensor W es: ")
print(w)

El tensor W es: 
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:

for i in range(3):
    for j in range(4):
        for k in range(2):
            w[i][j] = i**2 - j + 2*k

print("w modificado es: ")
print(w)
print("El elemento w[2,0,1] es: ", w[2][0][1])

w modificado es: 
[[[ 2.  2.]
  [ 1.  1.]
  [ 0.  0.]
  [-1. -1.]]

 [[ 3.  3.]
  [ 2.  2.]
  [ 1.  1.]
  [ 0.  0.]]

 [[ 6.  6.]
  [ 5.  5.]
  [ 4.  4.]
  [ 3.  3.]]]
El elemento w[2,0,1] es:  6.0


In [ ]:

v = np.array(([1, 2, 3, 4],
      [5 ,6, 7, 8],
      [9, 10, 11, 12],
      [13, 14, 15, 16]))
print("La matriz v es: ")
print(v)


La matriz v es: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
print("La matriz v sin la primer línea es: ")
print(v[1:, :])




La matriz v sin la primer línea es: 
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:

print("La matriz v sin la última línea es: ")
print(v[:-1, :])


La matriz v sin la última línea es: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:

print("La matriz v desde la columna 1 hasta la columna 2 es: ")
print(v[:, 1:3])


La matriz v desde la columna 1 hasta la columna 2 es: 
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:

print("La matriz reducida de v es: ")
print(v[1:3, 1:3])


La matriz reducida de v es: 
[[ 6  7]
 [10 11]]


In [ ]:

u = np.ones((5,5))
u[1:4,1:4] = 2
u[2:3,2:3] = 3
un = u.copy()
print("La matriz un es: ")
print(un)


La matriz un es: 
[[1. 1. 1. 1. 1.]
 [1. 2. 2. 2. 1.]
 [1. 2. 3. 2. 1.]
 [1. 2. 2. 2. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:

u[1:,1:] = un[1:,1:] - un[:-1,1:]

print("La matriz u modificada es: ")
print(u)

La matriz u modificada es: 
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  0.]
 [ 1.  0.  1.  0.  0.]
 [ 1.  0. -1.  0.  0.]
 [ 1. -1. -1. -1.  0.]]


## Ecuaciones diferenciales
Una ecuación diferencial es una ecuación que contiene una o mas funciones juntos con sus derivadas, el objetivo es encontrar la función que satisfaga la ecuación

Ejemplo:

$$\frac{d^2x}{dt^2}+\omega^2 x=0$$
tiene como solución la función $x(t) = A cos(\omega t)$, verifíquelo